### ISSUE TITLE
testing over ESP8266

### ISSUE THREAD

**Issue by marcolombardi-rm** [nadavmatalon/PCA9536#1]
I have tested the library with success over ESP8266 (Wemos D1 R2 on Arduino IDE). I think that you can extend the compatibility. Please consider this tip ;-)

**Comment by rtu-dataframe** [comment]
Also tested on ESP32, working good without any issue.

**Comment by nadavmatalon** [comment]
Thanks for the comments. I now removed the AVR architecture only check (see new ver 1.0.1).
